version: '3.8'
services:
  app:
    image: casamia
    container_name: casamia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
