# fly.toml app configuration file generated for casa-mia-winter-paper-7149 on 2025-03-06T14:40:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casa-mia'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
#put below on 'stop' when you want to save money
  auto_stop_machines = false
  auto_start_machines = true
#put below on 0 when you want to save money
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 2

[[scale]]
  units = 1